### ISSUE TITLE
2D LevelSet Curvature Square example

### ISSUE THREAD

**Issue by krismz** [SCIInstitute/SCI-Solver_Level-Set#3]
Running this example on Mac OSX 10.11 with GeForce GT650M and CUDA 7.5, I get a result0.vtk and result1.vtk file output that each have an empty volume of 0, 1 point scalar, 0 cell scalars.  What is the expected result for this example?

[curvature_square_results.zip](https://github.com/SCIInstitute/SCI-Solver_Level-Set/files/255388/curvature_square_results.zip)

**Comment by brigb123** [comment]
These results look correct. These are 2D (flat) meshes with differing values per vertex. You can see them properly in paraview.
